Fuji Network
aragon/dao-templates pull request #204
Opened 2021-11-05 03:14 UTC by maektwain

2021-11-05 03:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aragon/dao-templates?pullRequest=204) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aragon/dao-templates?pullRequest=204) before we can accept your contribution.<br/><hr/>**saransh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aragon/dao-templates?pullRequest=204) it.</sub>

2021-11-17 08:17 UTC, mathewmeconry requested changes

2021-11-17 09:51 UTC, Devilla commented on templates/open-enterprise/truffle-config.js
> +//config.networks.devnet.gas = gasLimit
Done! @mathewmeconry Please check.

2021-11-17 10:27 UTC, mathewmeconry approved these changes

2022-09-13 03:53 UTC, closed without merging